#!/usr/bin/env bash
# debugging nginx port 80
# How I solved it: delete the existing ../sites-enabled/default 
# ../sites-available/default. You do that by creating a symbolic link. 
# NB: The flag -s creates a symbolic link, -f deletes the existing file a
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart